name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'
          channel: 'stable'
      
      # Maine yahan folder ka path "mobile_app" set kar diya hai
      - name: Install Dependencies
        run: flutter pub get
        working-directory: mobile_app
        
      - name: Build APK
        run: flutter build apk --release
        working-directory: mobile_app
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: mobile_app/build/app/outputs/flutter-apk/app-release.apk
